version: '3'

networks:
  monorep_default:
    external: true

x-default: &default
  build:
    context: .
    dockerfile: Dockerfile.dev
  networks:
    - monorep_default

services:
  relay:
    <<: *default
    container_name: 2k_relay
    environment:
      ROCKET_ADDRESS: '0.0.0.0'
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - ./relay:/app/relay:ro
      - ./keys:/app/keys:rw

  manager:
    <<: *default
    container_name: 2k_manager
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [ "/usr/local/cargo/bin/cargo", "watch", "-w", "./manager", "-s", "cargo run --bin manager" ]
    environment:
      RELAY_ADDRESS: 'http://2k_relay:8000'
      AMQP_ADDRESS: 'amqp://guest:guest@2k_rabbitmq:5672//'
      VAULT_ADDRESS: 'http://2k_vault:8200'
    volumes:
      - ./manager:/app/manager:ro
