FROM rust:1.65

WORKDIR /app

RUN useradd -u 1000 -s /bin/bash -M -d /app 2k && \
    chown 1000:1000 -R /usr/local/cargo /app

USER 1000
RUN cargo install cargo-watch

COPY --chown=1000:1000 . /app/

RUN cargo build

CMD ["/usr/local/cargo/bin/cargo", "watch", "-w", "./relay", "-s", "cargo run --bin relay"]
