on:
  push:
    branches:
      - master
      - feature/ci-cd

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true # can cancel workflows scheduled later
  
  release:
    name: Release ${{ matrix.component.package }}-${{ matrix.component.binary}}-${{ matrix.target }} 
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false
      matrix:
        # target: [ x86_64-apple-darwin, x86_64-unknown-linux-musl, x86_64-pc-windows-gnu ]
        target: [ x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu, aarch64-apple-darwin ]
        component: [
          { package: "tss_cli", binary: "sign" },
          { package: "tss_cli", binary: "keygen" },
          { package: "manager", binary: "manager" },
        ]
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/setup/
        env:
          RUST_TARGET: ${{ matrix.target }}
      - name: Compile
        run: |
          cargo build --target ${{ matrix.target }} --release --package ${{ matrix.component.package }} --bin ${{ matrix.component.binary }}
      - name: Upload ${{ matrix.target }} binary to release
        uses: Spikatrix/upload-release-action@b713c4b73f0a8ddda515820c124efc6538685492
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.component.binary }}
          asset_name: ${{ matrix.component.binary }}-${{ matrix.target }}
          target_commit: ${{ github.sha }}
          tag: v${{ env.RELEASE_VERSION }}
          release_name: v${{ env.RELEASE_VERSION }}
          prerelease: false
          overwrite: true
          body: ${{ matrix.component.binary }} ${{ matrix.target }} release